// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.baza;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api.models.Drzava", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Drzava");
                });

            modelBuilder.Entity("api.models.Igrica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ProizvodacId")
                        .HasColumnType("int");

                    b.Property<decimal?>("cijena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("godinaIzdanja")
                        .HasColumnType("int");

                    b.Property<string>("naslov")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProizvodacId");

                    b.ToTable("Igrica");
                });

            modelBuilder.Entity("api.models.Proizvodac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("drzavaId")
                        .HasColumnType("int");

                    b.Property<string>("ime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("drzavaId");

                    b.ToTable("Proizvodac");
                });

            modelBuilder.Entity("api.models.Recenzije", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("igricaId")
                        .HasColumnType("int");

                    b.Property<string>("recenzija")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("igricaId");

                    b.ToTable("Recenzije");
                });

            modelBuilder.Entity("api.models.Igrica", b =>
                {
                    b.HasOne("api.models.Proizvodac", "Proizvodac")
                        .WithMany()
                        .HasForeignKey("ProizvodacId");

                    b.Navigation("Proizvodac");
                });

            modelBuilder.Entity("api.models.Proizvodac", b =>
                {
                    b.HasOne("api.models.Drzava", "drzava")
                        .WithMany()
                        .HasForeignKey("drzavaId");

                    b.Navigation("drzava");
                });

            modelBuilder.Entity("api.models.Recenzije", b =>
                {
                    b.HasOne("api.models.Igrica", "igrica")
                        .WithMany()
                        .HasForeignKey("igricaId");

                    b.Navigation("igrica");
                });
#pragma warning restore 612, 618
        }
    }
}
